### ISSUE TITLE
Question: about comaptibility to original folders2flickr

### ISSUE THREAD

**Issue by waywit** [richq/folders2flickr#38]
Hello

I am using folders2flickr for some time now, but the one from https://code.google.com/p/folders2flickr/
now I have uploaded many photos to flickr and a 10 MB "history" file from the old version...
Is it possible to upgrade to your version of folders2flickr and reuse the history file from the old version? I do not want to upload all the photos again to flickr... Perhaps someone has tried this and give some hints what to do?!?!

Tanks in advance and best regards
Jens

**Comment by richq** [comment]
Sorry for not replying to this. Did you see that one of the forks has a script to do this? Not sure how well it works though. https://github.com/go94022/folders2flickr/commit/6f3d9aa87f3692021caed2d6bc5b8c96a385ae0a
